@E_CommerceAPI_HostAddress = http://localhost:5000/api

 
GET {{E_CommerceAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

### Weatherforecast
GET {{E_CommerceAPI_HostAddress}}/weatherforecast/G

### Get All Products
GET {{E_CommerceAPI_HostAddress}}/Products